name:  Events Demo 1
on:
  pull_request:
    types:
      - opened
  workflow_dispatch:    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Output event - task: DownloadBuildArtifacts@0
        run: echo "${{ toJSON(github.event) }}"
      - name: Get - task: PublishCodeCoverageResults@1
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Test code 
        run: npm run test 
      - name: Build code 
        run: npm run Build
      - name: Deploy project
        run: echo "Deploying..." 